name: Building

on: [push]

env:
  SOLUTION_FILE_PATH: .
  
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Build Core
        run: |
          dotnet build Core/CTFAK.Core -f net6.0-windows -c Debug
          pwd
        
        
      - name: Build Decompiler
        run: dotnet build Plugins/CTFAK.Decompiler -f net6.0-windows -c Debug
      - name: Build Dumper
        run: dotnet build Plugins/Dumper -f net6.0-windows -c Debug
        
      - name: Build CTFAK.Cli     
        run: |
          dotnet publish Interface/CTFAK.Cli -f net6.0-windows -c Debug -r win-x64 -p:PublishSingleFile=true --self-contained false
          mkdir /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Cli/bin/Debug/net6.0-windows/win-x64/publish/Plugins
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/Dumper/bin/Debug/net6.0-windows/Dumper.dll /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Cli/bin/Debug/net6.0-windows/win-x64/publish/Plugins/Dumper.dll
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/Dumper/bin/Debug/net6.0-windows/Dumper.pdb /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Cli/bin/Debug/net6.0-windows/win-x64/publish/Plugins/Dumper.pdb
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/CTFAK.Decompiler/bin/Debug/net6.0-windows/CTFAK.Decompiler.dll /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Cli/bin/Debug/net6.0-windows/win-x64/publish/Plugins/CTFAK.Decompiler.dll
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/CTFAK.Decompiler/bin/Debug/net6.0-windows/CTFAK.Decompiler.pdb /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Cli/bin/Debug/net6.0-windows/win-x64/publish/Plugins/CTFAK.Decompiler.pdb
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/CTFAK.Decompiler/bin/Debug/net6.0-windows/CTFAK.Decompiler.pdb /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Cli/bin/Debug/net6.0-windows/win-x64/publish/Plugins/CTFAK.Decompiler.pdb
          cp -R /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Core/CTFAK.Core/x64 /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Cli/bin/Debug/net6.0-windows/win-x64/publish/
         
      - name: Prepare timing data
        run: date +%s > /opt/lampp/htdocs/ctfak/latestbuildid
      - name: Build CTFAK.Interactive
        run: |
          dotnet publish Interface/CTFAK.Interactive -f net7.0-windows -c Debug -r win-x64 -p:PublishSingleFile=true --self-contained false -p:SourceRevisionId=`cat /opt/lampp/htdocs/ctfak/latestbuildid`
          mkdir /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/Plugins
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/Dumper/bin/Debug/net6.0-windows/Dumper.dll /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/Plugins/Dumper.dll
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/Dumper/bin/Debug/net6.0-windows/Dumper.pdb /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/Plugins/Dumper.pdb
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/CTFAK.Decompiler/bin/Debug/net6.0-windows/CTFAK.Decompiler.dll /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/Plugins/CTFAK.Decompiler.dll
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/CTFAK.Decompiler/bin/Debug/net6.0-windows/CTFAK.Decompiler.pdb /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/Plugins/CTFAK.Decompiler.pdb
          cp -R /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Core/CTFAK.Core/x64 /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/
          cd /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/
          zip -r CTFAK.Interactive_Latest.zip *
          chmod 777 CTFAK.Interactive_Latest.zip
          cp CTFAK.Interactive_Latest.zip /opt/lampp/htdocs/ctfak/CTFAK.Interactive_Latest.zip
          rm CTFAK.Interactive_Latest.zip
          
      - name: Build CTFAK.Interactive (Self-contained)
        run: |
          dotnet publish Interface/CTFAK.Interactive -f net7.0-windows -c Debug -r win-x64 -p:PublishSingleFile=true --self-contained true -p:SourceRevisionId=`cat /opt/lampp/htdocs/ctfak/latestbuildid`
          mkdir /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/Plugins
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/Dumper/bin/Debug/net6.0-windows/Dumper.dll /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/Plugins/Dumper.dll
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/Dumper/bin/Debug/net6.0-windows/Dumper.pdb /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/Plugins/Dumper.pdb
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/CTFAK.Decompiler/bin/Debug/net6.0-windows/CTFAK.Decompiler.dll /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/Plugins/CTFAK.Decompiler.dll
          cp /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Plugins/CTFAK.Decompiler/bin/Debug/net6.0-windows/CTFAK.Decompiler.pdb /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/Plugins/CTFAK.Decompiler.pdb
          cp -R /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Core/CTFAK.Core/x64 /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/
          cd /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish/
          zip -r CTFAK.Interactive_Latest_SelfContained.zip *
          chmod 777 CTFAK.Interactive_Latest_SelfContained.zip
          cp CTFAK.Interactive_Latest_SelfContained.zip /opt/lampp/htdocs/ctfak/CTFAK.Interactive_Latest_SelfContained.zip
          rm CTFAK.Interactive_Latest_SelfContained.zip
        
      - name: Upload Core library
        uses: actions/upload-artifact@v2
        with:
          name: CTFAK.Core
          path: /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Core/CTFAK.Core/bin/Debug/net6.0-windows
          
      - name: Upload CLI tool
        uses: actions/upload-artifact@v2
        with:
          name: CTFAK.Cli
          path: /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Cli/bin/Debug/net6.0-windows/win-x64/publish
          
      - name: Upload Interactive console tool
        uses: actions/upload-artifact@v2
        with:
          name: CTFAK.Interactive
          path: /home/kostya/actions-runner/_work/CTFAK2.0/CTFAK2.0/Interface/CTFAK.Interactive/bin/Debug/net7.0-windows/win-x64/publish
    
      
